baseURL = 'https://tednoob17.github.io/'
languageCode = 'en-us'
title = 'Tedsig42'
theme = 'risotto'

# Main menu
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Friends"
    url = "/friends/"
    weight = 3
  [[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 4
  [[menu.main]]
    name = "Art"
    url = "/art/"
    weight = 5
  [[menu.main]]
    name = "Book Review"
    url = "/book-reviews/"
    weight = 6
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 6
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6    
[params]
  noindex = false
  favicon = "https://0xswitch.fr//static/img/gif/main-5.gif"
  [params.about]
    title = "Tedsig42"
    description = "Another infosec enthusiast blog"
    logo_image = "https://0xswitch.fr//static/img/gif/main-1.gif"

  [params.theme]
    palette = "tokyo-night-dark"

  [[params.socialLinks]]
    title = "GitHub"
    url = "https://github.com/Tednoob17"
    icon = "fab fa-github"

  [[params.socialLinks]]
    title = "Twitter"
    url = "https://twitter.com/Tedsig42"
    icon = "fab fa-twitter"

  [[params.socialLinks]]
    title = "Instagram"
    url = "https://instagram.com/tedsig_art"
    icon = "fab fa-instagram"
    
  [[params.socialLinks]]
    title = "LinkedIn"
    url = "https://linkedin.com/in/ted-kouhouenou"
    icon = "fab fa-linkedin"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
